baseURL = "https://feynmanliang.com/"
languageCode = "en-us"
title = "Feynman Liang"

theme = "slim"

[params]
  #Subtitle = "Your site's subtitle/tagline"
  GithubID = "feynmanliang"
  LinkedInID = "feynman"
  AnalyticsID = "UA-26556828-1"
  Summary = false
  Content = false
  FooterMsg = "Copyright Feynman Liang 2018. Powered by Hugo."

